name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # manual trigger
  jobs:
   build:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3     # Pulls your code from the repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest              # Runs any script in Repo that starts/Ends with test_

  deploy:
    name: Deploy to Cisco Sandbox
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script on Cisco sandbox
      env:
        DEVICE_HOSTS: ${{ secrets.DEVICE_HOSTS }}
        DEVICE_USERNAME: ${{ secrets.DEVICE_USERNAME }}
        DEVICE_PASSWORD: ${{ secrets.DEVICE_PASSWORD }}
      run: |
        python main.py
